"""
Django settings for digiinsurance project.

Generated by 'django-admin startproject' using Django 3.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from ._helper import getenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve(strict=True).parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'uc$$&#)*wuzl#hxnoqqq8=f$4=e&rwsgn@0q#2^y*^!_&_d(e3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # need to change to false (not sure)

# USE TO DISTINGUISH PROD SETTINGS AND DEV SETTINGS
IS_PRODUCTION = False
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '188.166.179.84', '128.199.223.101',
                 'https://di-admin-qyhq5.ondigitalocean.app', 'digiinsurance.qymera.tech', '13.212.253.175',
                 'nonprod-APPLB-801584624.ap-southeast-1.elb.amazonaws.com', '*']

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'mail.privateemail.com'
# EMAIL_HOST_USER = 'marketing@qymera.tech'
# EMAIL_HOST_PASSWORD = '(qDKdbBeQouU:'
# EMAIL_PORT = '587'
# EMAIL_USE_TLS = True

# http://www.google.com/accounts/DisplayUnlockCaptcha
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'vkalmazan@gmail.com'
EMAIL_HOST_PASSWORD = 'kkcztjmwpfhvxkri'  # kkcztjmwpfhvxkri

# EMAIL_ACTIVE_FIELD = 'is_activated'
# EMAIL_SERVER = 'smtp.gmail.com'
# EMAIL_MAIL_SUBJECT = 'Confirm your email'
# EMAIL_MAIL_HTML = 'verification.html'
# EMAIL_MAIL_PLAIN = 'verification.txt'
# EMAIL_PAGE_TEMPLATE = 'confirm_template.html'
# EMAIL_PAGE_DOMAIN = 'http://mydomain.com/' # the domain of the confirmation link (site's domain)
WEB_APP_URL = 'https://digiinsurance.qymera.tech'
WEB_APP_URL_ADMIN = 'https://di-admin-qyhq5.ondigitalocean.app'
WEB_APP_URL_LOCALHOST = 'localhost:8000'
# WEB_APP_DOMAIN = getenv('WEB_APP_DOMAIN', 'localhost')
# EMAIL_LIMIT = getenv('EMAIL_LIMIT', 1000)
# PUBLIC_PATH = getenv('PUBLIC_PATH', 'http://localhost:8889')
# WEB_DOMAIN = getenv('WEB_DOMAIN', '.localhost')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_dragonpay',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_yasg',
    'digiinsurance',
    'api',
    'kyc',
    'blockchain',
    'corsheaders',
    'storages',
    'django_extensions',
    'cocolife',
    'telco',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'digiinsurance.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'digiinsurance.wsgi.application'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_USER_MODEL = 'digiinsurance.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'templates'),
)

# STATIC_ROOT = '/home/django/DigiInsurance-backend/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# AWS SETTINGS
# USE_S3 = getenv('USE_S3', False)

if IS_PRODUCTION:
    AWS_ACCESS_KEY_ID = getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = 'https://nyc3.digitaloceanspaces.com'
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
#     AWS_LOCATION = 'media'
#     STATICFILES_DIRS = [
#         os.path.join(BASE_DIR, 'mysite/static'),
#     ]
#     STATIC_URL = 'https://%s/%s/' % (AWS_S3_ENDPOINT_URL, AWS_LOCATION)
#     STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# else:
#     STATIC_URL = '/static/'
#     MEDIA_URL = '/media/'

# CELERY
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_TASK_SERIALIZER = 'pickle'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ['pickle']
CELERY_TIMEZONE = 'UTC'

# CORS MIDDLEWARE
CORS_ORIGIN_ALLOW_ALL = True  # If this is used then `CORS_ORIGIN_WHITELIST` will not have any effect
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = [
    'https://localhost:3000', 'http://localhost:3000', 'http://localhost:3001', 'https://localhost:3001',
    'http://128.199.223.101', 'https://di-admin-qyhq5.ondigitalocean.app',
    'https://digiinsurance-yhrbl.ondigitalocean.app', 'https://digi-insurance-web-9d5ug.ondigitalocean.app',
    'https://digi-insurance-web-next-pxumm.ondigitalocean.app'
]  # If this is used, then not need to use `CORS_ORIGIN_ALLOW_ALL = True`
# CORS_ORIGIN_REGEX_WHITELIST = [
#    'http://localhost:3030',
# ]

# TWILIO

TWILIO_ACCOUNT_SERVICE_ID = "ACfd42b9d0a71aa4edf83f6b916f23b088"
TWILIO_AUTH_TOKEN = "ef811539b38158098759d391d54ed3ba"
TWILIO_VERIFY_SERVICE_ID = "VAe0150074916fa33c417adda3d78ed179"
