# Generated by Django 3.1 on 2021-10-19 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digiinsurance', '0021_auto_20211011_1601'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CLFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('feature_name', models.CharField(max_length=50, unique=True)),
                ('is_feature_active', models.BooleanField(default=False)),
                ('client_type', models.CharField(choices=[('MO', 'Mobile'), ('CL', 'Client'), ('AD', 'Admin')], default='AD', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DigiInsuree',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='DigiInsuree', serialize=False, to='digiinsurance.user')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True)),
                ('mobile_number', models.CharField(max_length=16, null=True, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('current_add', models.CharField(blank=True, max_length=555, null=True)),
                ('occupation', models.CharField(blank=True, max_length=555, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=64, null=True)),
                ('nationality', models.CharField(blank=True, max_length=16, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=64, null=True)),
                ('sss', models.CharField(blank=True, max_length=16, null=True)),
                ('tin', models.CharField(blank=True, max_length=16, null=True)),
                ('business', models.CharField(blank=True, max_length=16, null=True)),
                ('tel_number', models.CharField(blank=True, max_length=16, null=True)),
                ('home_add', models.CharField(blank=True, max_length=555, null=True)),
                ('home_country', models.CharField(blank=True, max_length=16, null=True)),
                ('home_zip_code', models.CharField(blank=True, max_length=4, null=True)),
                ('current_country', models.CharField(blank=True, max_length=16, null=True)),
                ('current_zip_code', models.CharField(blank=True, max_length=4, null=True)),
                ('employer', models.CharField(blank=True, max_length=16, null=True)),
                ('nature_of_business_of_employer', models.CharField(blank=True, max_length=16, null=True)),
                ('isArchived', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('N', 'New'), ('E', 'Existing'), ('O', 'Others')], default='N', max_length=1, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InsureePolicyIssuanceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('policy', models.BooleanField(default=True)),
                ('insuree', models.BooleanField(default=True)),
                ('status', models.BooleanField(default=True)),
                ('premium_amount_due', models.BooleanField(default=True)),
                ('premium_date_due', models.BooleanField(default=True)),
                ('premium_last_paid', models.BooleanField(default=True)),
                ('premium_last_date', models.BooleanField(default=True)),
                ('policy_type', models.BooleanField(default=True)),
                ('policy_type2', models.BooleanField(default=True)),
                ('active_premium_interval', models.BooleanField(default=True)),
                ('Currency', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image_path', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=models.CharField(blank=True, max_length=32, null=True))),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('life', 'Life'), ('health', 'Health'), ('home', 'Home'), ('car', 'Car'), ('vul', 'VUL')], max_length=64, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('draft', 'Draft')], max_length=64, null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('passing_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='cocolife.package')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Underwriting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('insuree_policy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='underwriting', serialize=False, to='digiinsurance.insureepolicy')),
                ('underwriter_status', models.CharField(choices=[('pending', 'PENDING'), ('approved', 'APPROVED'), ('denied', 'DENIED')], default='PENDING', max_length=64)),
                ('editor', models.ForeignKey(default=375, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductInsuree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('face_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.CharField(choices=[('annual', 'Annual'), ('semi_annual', 'Semi Annual'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='monthly', max_length=30)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=10)),
                ('premium_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_due_date', models.DateField(blank=True, null=True)),
                ('premium_last_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium_last_date', models.DateField(blank=True, null=True)),
                ('billed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productinsurees', to='cocolife.DigiInsuree')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productinsurees', to='cocolife.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('coverage_term', models.IntegerField()),
                ('age_bracket', models.CharField(blank=True, choices=[('5 to 17', '5 to 17'), ('18 to 45', '18 to 45'), ('46 to 55', '46 to 55'), ('56 to 64', '56 to 64')], max_length=64, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premiums', to='cocolife.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32)),
                ('mobile_number', models.CharField(max_length=16, null=True, unique=True)),
                ('tel_number', models.CharField(blank=True, max_length=16, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=555, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=64, null=True)),
                ('nationality', models.CharField(blank=True, max_length=16, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=64, null=True)),
                ('sss', models.CharField(blank=True, max_length=16, null=True)),
                ('tin', models.CharField(blank=True, max_length=16, null=True)),
                ('business', models.CharField(blank=True, max_length=16, null=True)),
                ('home_add', models.CharField(blank=True, max_length=555, null=True)),
                ('home_village', models.CharField(blank=True, max_length=16, null=True)),
                ('home_city', models.CharField(blank=True, max_length=4, null=True)),
                ('home_country', models.CharField(blank=True, max_length=16, null=True)),
                ('home_zip_code', models.CharField(blank=True, max_length=4, null=True)),
                ('nature_of_business', models.CharField(blank=True, max_length=16, null=True)),
                ('specified_source', models.CharField(blank=True, max_length=50, null=True)),
                ('source_of_funds', models.CharField(blank=True, max_length=50, null=True)),
                ('office_add', models.CharField(blank=True, max_length=555, null=True)),
                ('office_zip_code', models.CharField(blank=True, max_length=4, null=True)),
                ('office_country', models.CharField(blank=True, max_length=16, null=True)),
                ('insured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiinsurance.insuree')),
                ('insuree_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiinsurance.insureepolicy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='cocolife.product'),
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('face_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='cocolife.variant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contact_no', models.CharField(max_length=20)),
                ('birth_place', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('citizenship', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=10)),
                ('relationship', models.CharField(max_length=50)),
                ('percentage_share', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('priority_type', models.CharField(choices=[('Primary', 'PRIMARY'), ('Contingent', 'CONTINGENT')], max_length=20)),
                ('benefit_type', models.CharField(choices=[('Revocable', 'REVOCABLE'), ('Irrevocable', 'IRREVOCABLE')], max_length=20)),
                ('product_insuree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocolife.productinsuree')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAssisted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agentassists', to='cocolife.DigiInsuree')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
