# Generated by Django 3.1 on 2021-10-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyowner',
            name='insured_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocolife.DigiInsuree'),
        ),
        migrations.AlterField(
            model_name='policyowner',
            name='insuree_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocolife.productinsuree'),
        ),
        migrations.AlterField(
            model_name='underwriting',
            name='insuree_policy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='underwriting', serialize=False, to='cocolife.productinsuree'),
        ),
    ]
