# Generated by Django 3.1 on 2021-10-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coverage_amount_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='coverage_amount_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
