# Generated by Django 3.1 on 2021-10-19 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0002_clhealthquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLHealthQuestionsAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=256, null=True)),
                ('answer_status', models.CharField(choices=[('Pass', 'pass'), ('Fail', 'fail'), ('Not Answered', 'not_answered')], default='Not Answered', max_length=256)),
                ('ProdInsuree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocolife.productinsuree')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocolife.clhealthquestions')),
            ],
        ),
    ]
