# Generated by Django 3.1 on 2021-10-20 10:01

import cocolife.models.CLAdvertisements
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0002_auto_20211019_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLAdvertisements',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[
                 ('article', 'Article'), ('promo', 'Promo')], max_length=30, null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publish_date', models.DateField(default=datetime.date.today)),
                ('expiration_date', models.DateField(default=datetime.date.today)),
                ('photo', models.ImageField(blank=True, null=True,
                                            upload_to=cocolife.models.upload_image)),
                ('status', models.CharField(max_length=20, null=True)),
                ('view_count', models.IntegerField(
                    blank=True, default=0, null=True)),
                ('liked', models.ManyToManyField(blank=True, default=None,
                                                 related_name='liked', to='cocolife.DigiInsuree')),
                ('product', models.ForeignKey(blank=True, default=2, null=True,
                                              on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cocolife.product')),
            ],
        ),
    ]
