# Generated by Django 3.1 on 2021-10-20 05:42

from cocolife.models.Product import upload_product_pdf, img_upload_dir
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0003_auto_20211020_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=img_upload_dir),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=upload_product_pdf),
        ),
    ]
