# Generated by Django 3.1 on 2021-10-20 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0003_cladvertisements'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentassisted',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='agentassists', to='cocolife.product'),
            preserve_default=False,
        ),
    ]
