# Generated by Django 3.1 on 2021-10-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0003_clhealthquestionsanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='clhealthquestions',
            name='is_adult',
            field=models.BooleanField(default=True),
        ),
    ]
