# Generated by Django 3.1 on 2021-10-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0004_agentassisted_product'),
        ('cocolife', '0004_auto_20211020_1342'),
    ]

    operations = [
    ]
