# Generated by Django 3.1 on 2021-10-20 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0005_merge_20211020_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinsuree',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productinsurees', to='cocolife.package'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productinsuree',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productinsurees', to='cocolife.variant'),
            preserve_default=False,
        ),
    ]
