# Generated by Django 3.1 on 2021-10-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0004_clhealthquestions_is_adult'),
        ('cocolife', '0006_auto_20211020_1736'),
    ]

    operations = [
    ]
