# Generated by Django 3.1 on 2021-10-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0007_merge_20211020_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinsuree',
            name='face_amount',
        ),
        migrations.AddField(
            model_name='productinsuree',
            name='coverage_term',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
