# Generated by Django 3.1 on 2021-10-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0008_auto_20211020_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='premium',
            name='age_bracket',
        ),
        migrations.AddField(
            model_name='premium',
            name='age_max',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='premium',
            name='age_min',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
