# Generated by Django 3.1 on 2021-10-25 03:57

import cocolife.models.DigiKYC
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_auto_20211011_1601'),
        ('cocolife', '0009_auto_20211020_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocoUserID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo_id', models.ImageField(blank=True, null=True, upload_to=cocolife.models.DigiKYC.upload_photo_id)),
                ('photo_id_back', models.ImageField(default='', upload_to=cocolife.models.DigiKYC.upload_photo_id_back)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to=cocolife.models.DigiKYC.upload_selfie)),
                ('verified', models.BooleanField(default=False)),
                ('encoded', models.JSONField(null=True)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.templateid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ids', to='cocolife.DigiInsuree')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
