# Generated by Django 3.1 on 2021-10-25 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0010_cltransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cltransaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cltransaction',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='cltransaction',
            name='productinsuree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_transactions', to='cocolife.productinsuree'),
        ),
    ]
