# Generated by Django 3.1 on 2021-10-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0011_auto_20211025_1542'),
        ('cocolife', '0010_cocouserid'),
        ('cocolife', '0012_policyowner'),
    ]

    operations = [
    ]
