# Generated by Django 3.1 on 2021-10-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0013_merge_20211029_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('download', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
