# Generated by Django 3.1 on 2021-11-02 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0014_appstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_prod', to='cocolife.DigiInsuree'),
        ),
    ]
