# Generated by Django 3.1 on 2021-11-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0014_appstat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyowner',
            name='email',
            field=models.EmailField(max_length=128),
        ),
        migrations.AlterField(
            model_name='policyowner',
            name='mobile_number',
            field=models.CharField(max_length=16),
        ),
    ]
