# Generated by Django 3.1 on 2021-11-03 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0015_auto_20211103_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyowner',
            name='product_insuree',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cocolife.productinsuree'),
        ),
    ]
