# Generated by Django 3.1 on 2021-11-05 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0016_auto_20211103_1313'),
        ('cocolife', '0015_product_liked'),
    ]

    operations = [
    ]
