# Generated by Django 3.1 on 2021-11-09 07:14

import cocolife.models.CompanyInformation
from django.db import migrations, models
from cocolife.models.CompanyInformation import upload_pdf_COA, upload_pdf_DPI, upload_pdf_FAQ


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0017_merge_20211109_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('pdf_coa', models.FileField(blank=True, null=True, upload_to=upload_pdf_COA)),
                ('pdf_dpi', models.FileField(blank=True, null=True, upload_to=upload_pdf_DPI)),
                ('pdf_faq', models.FileField(blank=True, null=True, upload_to=upload_pdf_FAQ)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
