# Generated by Django 3.1 on 2021-11-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0017_merge_20211105_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='DigiInsuree',
            name='default_contact_info',
            field=models.CharField(choices=[('email', 'Email'), ('mobile', 'Mobile')], default='email', max_length=16),
        ),
        migrations.AlterField(
            model_name='ProductInsuree',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='inactive', max_length=10),
        ),
    ]
