# Generated by Django 3.1 on 2021-11-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0018_auto_20211105_1210'),
        ('cocolife', '0018_companyinformation'),
    ]

    operations = [
    ]
