# Generated by Django 3.1 on 2021-11-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0019_merge_20211111_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='DigiInsuree',
            name='default_contact_info',
            field=models.CharField(choices=[('email', 'Email'), ('mobile', 'Mobile'), ('landline', 'Landline')], default='email', max_length=16),
        ),
        migrations.AlterField(
            model_name='ProductInsuree',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('lapsed', 'Lapsed'), ('ended', 'Ended')], default='inactive', max_length=10),
        ),
    ]
