# Generated by Django 3.1 on 2022-10-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0020_auto_20211112_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='DigiInsuree',
            name='mobile_number',
            field=models.CharField(max_length=16),
        ),
    ]
