# Generated by Django 3.1 on 2023-01-30 03:02

import cocolife.models.Product
from django.db import migrations, models

from cocolife.models.Product import default_json_value

class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0021_auto_20221024_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.JSONField(blank=True, default=default_json_value, null=True),
        ),
    ]
