# Generated by Django 3.1 on 2023-03-03 09:50

import cocolife.models.Inquiry
import cocolife.models.Product
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from cocolife.models.Product import default_json_value
from cocolife.models.Inquiry import upload_img_attachment


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0005_auto_20211011_1601'),
        ('cocolife', '0022_auto_20230130_1102'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='APIKey',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('modified_at', models.DateTimeField(auto_now=True)),
        #         ('key', models.CharField(max_length=255, unique=True)),
        #         ('value', models.TextField()),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='APILogger',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('modified_at', models.DateTimeField(auto_now=True)),
        #         ('api_call', models.CharField(blank=True, max_length=255, null=True)),
        #         ('response', models.JSONField(null=True)),
        #         ('status', models.BooleanField()),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='AuditLog',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('modified_at', models.DateTimeField(auto_now=True)),
        #         ('action', models.CharField(blank=True, max_length=255, null=True)),
        #         ('user_id', models.CharField(blank=True, max_length=255, null=True)),
        #         ('details_id', models.CharField(blank=True, max_length=255, null=True)),
        #         ('ip_address', models.CharField(blank=True, max_length=255, null=True)),
        #         ('login_user', models.CharField(blank=True, max_length=255, null=True)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='DepartmentEmail',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('modified_at', models.DateTimeField(auto_now=True)),
        #         ('inquiry_type', models.CharField(blank=True, max_length=100, null=True)),
        #         ('mailto', models.JSONField(blank=True, default=list, null=True)),
        #         ('cc', models.JSONField(blank=True, default=list, null=True)),
        #         ('bcc', models.JSONField(blank=True, default=list, null=True)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        # migrations.RenameModel(
        #     old_name='CLTransaction',
        #     new_name='DigiTransaction',
        # ),
        # migrations.RenameModel(
        #     old_name='CocoUserID',
        #     new_name='DigiUserID',
        # ),
        # migrations.RenameField(
        #     model_name='clhealthquestionsanswers',
        #     old_name='ProdInsuree',
        #     new_name='product_insuree',
        # ),
        # migrations.AddField(
        #     model_name='package',
        #     name='year_selection',
        #     field=models.JSONField(blank=True, default=default_json_value, null=True),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='active_flag',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='author',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_author', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='call_agent_flag',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='editor',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_editor', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='interested',
        #     field=models.ManyToManyField(blank=True, default=None, related_name='interested_products', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='isArchived',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='is_agent_assisted',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='product_benefits',
        #     field=models.TextField(blank=True, default='', null=True),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='product_packages',
        #     field=models.TextField(blank=True, default='', null=True),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='purchase_flag',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='product',
        #     name='type_of_need',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AddField(
        #     model_name='variant',
        #     name='name',
        #     field=models.CharField(blank=True, max_length=255, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='digiinsuree',
        #     name='user',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='digiinsuree', serialize=False, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='product',
        #     name='liked',
        #     field=models.ManyToManyField(blank=True, default=None, related_name='liked_prod', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.CreateModel(
        #     name='Profile',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('modified_at', models.DateTimeField(auto_now=True)),
        #         ('email', models.EmailField(max_length=128)),
        #         ('first_name', models.CharField(blank=True, max_length=255, null=True)),
        #         ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
        #         ('last_name', models.CharField(blank=True, max_length=255, null=True)),
        #         ('mobile_number', models.CharField(max_length=16)),
        #         ('gender', models.CharField(blank=True, choices=[('F', 'Femal'), ('M', 'Male')], max_length=1, null=True)),
        #         ('birthday', models.DateField(blank=True, default='1900-05-05', null=True)),
        #         ('tel_number', models.CharField(blank=True, max_length=16, null=True)),
        #         ('occupation', models.CharField(blank=True, max_length=64, null=True)),
        #         ('civil_status', models.CharField(blank=True, max_length=64, null=True)),
        #         ('nationality', models.CharField(blank=True, max_length=64, null=True)),
        #         ('place_of_birth', models.CharField(blank=True, max_length=128, null=True)),
        #         ('sss', models.CharField(blank=True, max_length=16, null=True)),
        #         ('tin', models.CharField(blank=True, max_length=16, null=True)),
        #         ('business', models.CharField(blank=True, max_length=64, null=True)),
        #         ('home_address', models.CharField(blank=True, max_length=255, null=True)),
        #         ('home_village', models.CharField(blank=True, max_length=255, null=True)),
        #         ('home_city', models.CharField(blank=True, max_length=64, null=True)),
        #         ('home_province', models.CharField(blank=True, max_length=64, null=True)),
        #         ('home_zip_code', models.CharField(blank=True, max_length=10, null=True)),
        #         ('nature_of_business', models.CharField(blank=True, max_length=64, null=True)),
        #         ('specified_source', models.CharField(blank=True, max_length=64, null=True)),
        #         ('source_of_funds', models.CharField(blank=True, max_length=64, null=True)),
        #         ('office_address', models.CharField(blank=True, max_length=255, null=True)),
        #         ('office_village', models.CharField(blank=True, max_length=255, null=True)),
        #         ('office_city', models.CharField(blank=True, max_length=64, null=True)),
        #         ('office_province', models.CharField(blank=True, max_length=255, null=True)),
        #         ('office_zip_code', models.CharField(blank=True, max_length=64, null=True)),
        #         ('isArchived', models.BooleanField(default=False)),
        #         ('tags', models.TextField(blank=True, null=True)),
        #         ('default_contact_num', models.CharField(blank=True, choices=[('email', 'Email'), ('mobile', 'Mobile'), ('landline', 'Landline')], max_length=16, null=True)),
        #         ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Inquiry',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('created_at', models.DateTimeField(auto_now_add=True)),
        #         ('modified_at', models.DateTimeField(auto_now=True)),
        #         ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
        #         ('inquiry_type', models.CharField(blank=True, max_length=100, null=True)),
        #         ('subject', models.CharField(blank=True, max_length=100, null=True)),
        #         ('concern', models.TextField()),
        #         ('attachment', models.ImageField(blank=True, null=True, upload_to=upload_img_attachment)),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inquiries', to=settings.AUTH_USER_MODEL)),
        #     ],
        #     options={
        #         'abstract': False,
        #     },
        # ),
    ]
