# Generated by Django 3.1 on 2023-02-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0022_auto_20230130_1102'),
    ]

    operations = [
    ]
