# Generated by Django 3.1 on 2023-03-06 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocolife', '0023_auto_20230303_1750'),
        ('cocolife', '0023_auto_20230201_1704'),
    ]

    operations = [
    ]
