# Generated by Django 3.1 on 2021-07-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insureepolicy',
            name='policy_type2',
            field=models.CharField(choices=[('lite', 'Lite'), ('pro', 'Pro'), ('standard', 'Standard'), ('basic', 'Basic')], default='Lite', max_length=10),
        ),
    ]
