# Generated by Django 3.2.3 on 2021-07-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0002_auto_20210715_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='claims',
            name='claim_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending')], default='Pending', max_length=10),
        ),
    ]
