# Generated by Django 3.1 on 2021-07-23 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0003_policy_passing_score'),
        ('digiinsurance', '0003_claims_claim_status'),
    ]

    operations = [
    ]
