# Generated by Django 3.1 on 2021-07-23 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0004_merge_20210723_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='company',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Policies', to='digiinsurance.company'),
        ),
    ]
