# Generated by Django 3.1 on 2021-07-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0006_auto_20210727_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='mobile_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=None, max_length=16, unique=True),
        ),
    ]
