# Generated by Django 3.1.6 on 2021-08-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0006_auto_20210727_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='Title',
            field=models.CharField(max_length=255),
        )
    ]
