# Generated by Django 3.1.6 on 2021-08-02 09:31

import digiinsurance.models.Policy
from django.db import migrations, models
from digiinsurance.models.Policy import pdf_path


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0006_auto_20210727_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='Policy',
            name='benefits_basic',
            field=models.FileField(blank=True, null=True, upload_to=pdf_path),
        ),
        migrations.AddField(
            model_name='Policy',
            name='benefits_lite',
            field=models.FileField(blank=True, null=True, upload_to=pdf_path),
        ),
        migrations.AddField(
            model_name='Policy',
            name='benefits_pro',
            field=models.FileField(blank=True, null=True, upload_to=pdf_path),
        ),
        migrations.AddField(
            model_name='Policy',
            name='benefits_standard',
            field=models.FileField(blank=True, null=True, upload_to=pdf_path),
        )
    ]
