# Generated by Django 3.1 on 2021-08-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0007_auto_20210803_1528'),
        ('digiinsurance', '0007_auto_20210802_1731'),
        ('digiinsurance', '0007_auto_20210728_1256'),
        ('digiinsurance', '0007_auto_20210804_1328'),
    ]

    operations = [
    ]
