# Generated by Django 3.1 on 2021-08-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0008_merge_20210805_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='claim_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
