# Generated by Django 3.1.6 on 2021-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0009_auto_20210805_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaries',
            name='reason',
            field=models.CharField(default='Reason', max_length=255),
        ),
    ]
