# Generated by Django 3.1.6 on 2021-08-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0012_auto_20210810_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiaries',
            old_name='benefeciary_status',
            new_name='beneficiary_status',
        ),
    ]
