# Generated by Django 3.1 on 2021-08-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0014_auto_20210813_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='mobile_number',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=None, max_length=16, null=True, unique=True),
        ),
    ]
