# Generated by Django 3.1 on 2021-08-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0010_termsandcondition'),
        ('digiinsurance', '0015_auto_20210818_2323'),
    ]

    operations = [
    ]
