# Generated by Django 3.1 on 2021-08-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0016_merge_20210825_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='termsandcondition',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms_and_conditions', to='digiinsurance.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=None, max_length=16, unique=True),
        ),
    ]
