# Generated by Django 3.1 on 2021-09-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0018_policy_is_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True),
        ),
    ]

