# Generated by Django 3.2.6 on 2021-09-22 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0019_auto_20210916_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(blank=True, max_length=256, null=True)),
                ('question', models.CharField(max_length=256, null=True)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digiinsurance.company')),
            ],
        ),
    ]
