# Generated by Django 3.1 on 2021-10-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0020_companyfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('IN', 'Insuree'), ('CO', 'Insurance Admin'), ('ST', 'Insurance Staff'), ('UW', 'Underwriter'), ('AD', 'Admin')], max_length=2),
        ),
    ]
