# Generated by Django 3.1 on 2022-10-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0021_auto_20211011_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuree',
            name='mobile_number',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='mobile_number',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
