# Generated by Django 3.1 on 2023-03-03 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('digiinsurance', '0022_auto_20221024_1611'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='healthquestionsanswers',
        #     old_name='insureePolicy',
        #     new_name='insuree_policy',
        # ),
        # migrations.RemoveField(
        #     model_name='transaction',
        #     name='insureePolicy',
        # ),
        # migrations.AddField(
        #     model_name='staff',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='transaction',
        #     name='insuree_policy',
        #     field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='insuree_policy', to='digiinsurance.insureepolicy'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='created_at',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='department',
        #     field=models.CharField(blank=True, default=None, max_length=16, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='device',
        #     field=models.CharField(blank=True, default=None, max_length=16, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='email_otp',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='email_otp_created_at',
        #     field=models.DateTimeField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='is_archived',
        #     field=models.BooleanField(default=False),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='is_otp_active',
        #     field=models.BooleanField(default=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='modified_at',
        #     field=models.DateTimeField(auto_now=True),
        # ),
        # migrations.AddField(
        #     model_name='user',
        #     name='tags',
        #     field=models.CharField(blank=True, choices=[('Policy Holder', 'Policy Holder'), ('Non Policy Holder', 'Non Policy Holder')], default='Non Policy Holder', max_length=30, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='insuree',
        #     name='mobile_number',
        #     field=models.CharField(max_length=16, null=True, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='insuree',
        #     name='user',
        #     field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Insuree', serialize=False, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='insureepolicy',
        #     name='policy',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insuree_policies', to='digiinsurance.policy'),
        # ),
        # migrations.AlterField(
        #     model_name='staff',
        #     name='mobile_number',
        #     field=models.CharField(max_length=16, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='staff',
        #     name='user_id',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.AlterField(
        #     model_name='transaction',
        #     name='channel',
        #     field=models.CharField(blank=True, choices=[('full', 'Full Payment'), ('loan', 'Loan Payment')], max_length=32, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='transaction',
        #     name='description',
        #     field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='transaction',
        #     name='insuree',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='digiinsurance.insuree'),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='email',
        #     field=models.EmailField(max_length=128),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='mobile_number',
        #     field=models.CharField(blank=True, default=None, max_length=16, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='user',
        #     name='role',
        #     field=models.CharField(choices=[('IN', 'Insuree'), ('CO', 'Insurance Admin'), ('ST', 'Insurance Staff'), ('UW', 'Underwriter'), ('AD', 'Admin'), ('AG', 'Agent'), ('ED', 'Editor'), ('SL', 'Sales'), ('AN', 'Analyst')], max_length=2),
        # ),
        # migrations.AlterField(
        #     model_name='userbankaccount',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userbankaccount', to=settings.AUTH_USER_MODEL),
        # ),
        # migrations.DeleteModel(
        #     name='CompanyConfig',
        # ),
    ]
