# Generated by Django 3.1 on 2022-10-21 14:19

from django.db import migrations, models
import telco.models


class Migration(migrations.Migration):

    dependencies = [
        ('telco', '0002_telcosimdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelcoCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cert_of_registration', models.FileField(blank=True, null=True, upload_to=telco.models.cert_of_registration)),
                ('resolution', models.FileField(blank=True, null=True, upload_to=telco.models.resolution)),
                ('power_attorney', models.FileField(blank=True, null=True, upload_to=telco.models.power_attorney)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
