# Generated by Django 3.1 on 2022-10-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telco', '0003_telcocompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='telcosimdetails',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
