# Generated by Django 3.1 on 2022-10-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telco', '0004_telcosimdetails_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telcosimdetails',
            name='isActive',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
