# Generated by Django 3.1 on 2022-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telco', '0006_jumiotoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='jumiotoken',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
