# Generated by Django 3.1 on 2022-10-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telco', '0007_jumiotoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='telcopersonaddress',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
