# Generated by Django 3.1 on 2020-09-01 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kyc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=64)),
                ('template_id', models.ImageField(upload_to=kyc.models.upload_template_id)),
                ('institute_name', models.CharField(max_length=128)),
                ('institute', models.CharField(max_length=32)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('photo_id', models.ImageField(blank=True, null=True, upload_to=kyc.models.upload_photo_id)),
                ('selfie', models.ImageField(blank=True, null=True, upload_to=kyc.models.upload_selfie)),
                ('verified', models.BooleanField(default=False)),
                ('encoded', models.JSONField()),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kyc.templateid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
