# Generated by Django 3.1 on 2020-09-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userid',
            name='encoded',
            field=models.JSONField(null=True),
        ),
    ]
