# Generated by Django 3.1 on 2021-03-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20200926_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templateid',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='templateid',
            name='last_name',
        ),
    ]
