# Generated by Django 3.1 on 2021-07-13 06:38

from django.db import migrations, models
import kyc.models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20210324_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='userid',
            name='photo_id_back',
            field=models.ImageField(default='', upload_to=kyc.models.upload_photo_id_back),
        ),
    ]
