# Generated by Django 3.1 on 2021-10-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_userid_photo_id_back'),
    ]

    operations = [
        
    ]
